[settings.general]
seed = 42

[paths]
output_dir = "/data/"
models = "/models/"

[path.mlflow]
tracking_uri = "../mlruns/pre/"

[paths.data]
encoded_data = "/data/data_encoded.parquet"
raw_data = "/data/term-deposit-marketing-2020.csv"
raw_pdata = "/data/term_deposit-policy.parquet"
pre= "/data/data_precall_encoded.parquet"
post= "data/data_postcall_encoded.parquet"


[paths.TPOT]
periodic_checkpoint_folder = "../models/tpot/pre/checkpoints/"
base = "../models/tpot/pre/"

[database]
host = 'localhost'
port = 5432
user = 'your_username'
password = 'your_password'
database_name = 'your_database'

[settings.H2O]
project_name = "term_deposit_prediction"
max_models = 20
stopping_metric = "AUC"
export_checkpoints_dir = "/path/to/export/checkpoints"
nfolds = 5
max_runtime_secs = 5000
seed = 42
verbosity = "warn"
# balance_classes = true

# TPOT Classifier Configuration
[TPOT.one]
generations = 5
population_size = 20
verbosity = 0
use_dask = false
cv = 5
random_state = 42
scoring = "precision"

[TPOT.two]
generations = 1
population_size = 50
verbosity = 2
use_dask = false
cv = 5
random_state = 42
scoring = "precision"

[automl]
task = "regression"
log_file_name = "../models/flaml/logs.log"
n_jobs = -1
estimator_list = "auto"
time_budget = 600
max_iter = 1000000
sample = true
ensemble = false