name: term_deposit-causal
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - statsmodels
  - dowhy
  - tabulate
  - pygraphviz
  - imbalanced-learn
  - fastparquet
  - tpot
  - dask
  - pip:
    - causalinference
    - causalml
    - graphviz
    - causalnex
    - causal-learn
    - econml