name: term_deposit-cluster
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - tabulate
  - fastparquet
  - tpot
  - pip
  - pip:
    - umap-learn
    - clustpy[full]