experimentName: customer_subscription_classification
trialConcurrency: 1
maxTrialNumber: 50
searchSpaceFile: search_space.json
tuner:
  name: TPE  # Tree-structured Parzen Estimator for Bayesian Optimization
  classArgs:
    optimize_mode: maximize
trial:
  command: python nni_train.py
  codeDir: .
  gpuNum: 0
